amazon:
  access:
    key: <Enter your access Key>
    secret-key:  <Enter your secret key>
  region: us-east-2
  end-point:
#    url: https://dynamodb.us-east-2.amazonaws.com
    url: dynamodb.us-east-2.amazonaws.com

server:
  port: 9001


