amazon:
  access:
    key: AKIASSZPC5C2K2J55IE4
    secret-key: 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
  region: us-east-2
  end-point:
#    url: https://dynamodb.us-east-2.amazonaws.com
    url: dynamodb.us-east-2.amazonaws.com

server:
  port: 9001


