amazon:
  access:
    key: AKIASSZPC5C2IFE3U4NV
    secret-key:  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
  region: us-east-2
  end-point:
#    url: https://dynamodb.us-east-2.amazonaws.com
    url: dynamodb.us-east-2.amazonaws.com

server:
  port: 9001


